"""create release_step_execution

Revision ID: 77fa95ecd37b
Revises: 528447aa8a58
Create Date: 2026-05-23 11:48:56.663715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77fa95ecd37b'
down_revision: Union[str, Sequence[str], None] = '528447aa8a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_step_execution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('release_process_id', sa.String(), nullable=False),
    sa.Column('stage_id', sa.String(), nullable=False),
    sa.Column('step_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_release_step_execution_process_stage_step', 'release_step_execution', ['release_process_id', 'stage_id', 'step_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_release_step_execution_process_stage_step', table_name='release_step_execution')
    op.drop_table('release_step_execution')
    # ### end Alembic commands ###
