"""add_users_table

Revision ID: 7e5906e5458f
Revises: g7b8c9d0e1f2
Create Date: 2026-06-20 11:38:52.008955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5906e5458f'
down_revision: Union[str, Sequence[str], None] = 'g7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    with op.batch_alter_table('step_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_event_correlation_id'))
        batch_op.create_index(batch_op.f('ix_step_event_job_execution_correlation_id'), ['job_execution_correlation_id'], unique=False)

    # Seed initial admin user
    op.execute(
        "INSERT INTO user (username, password_hash, \"group\", created_at, updated_at) "
        "VALUES ('admin', '$2b$12$dNIygxvZJGrYfDM2DY1FAu/0a.RmcEsnUhtfaVN5AFwZ00NDZGMMy', 'Administrators', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_event_job_execution_correlation_id'))
        batch_op.create_index(batch_op.f('ix_step_event_correlation_id'), ['job_execution_correlation_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    # ### end Alembic commands ###
